name: 'CloudFormation Deploy'
description: 'Create or update a CloudFormation stack using the AWS CLI'
inputs:
  stackName:
    description: 'Name of the stack to be passed to the --stack-name argument of the AWS CLI'
    required: true
  templateFile:
    description: 'Path to the template file to be passed to the --template-file argument of the AWS CLI'
    required: true
  hasIAMCapability:
    description: 'Determines whether to pass CAPABILITY_IAM as a capability'
    required: false
    default: false
  hasIAMNamedCapability:
    description: 'Determines whether to pass CAPABILITY_NAMED_IAM as a capability'
    required: false
    default: false
outputs:
  stackOutputs:
    description: 'Stack outputs returned by the AWS CloudFormation describe-stacks command'
runs:
  using: 'node12'
  main: 'dist/index.js'
